export const NotificationTypes = {
    MATCH_REQUEST: 'MATCH_REQUEST',
    MATCH_APPROVE: 'MATCH_APPROVE',
    MATCH_REJECT: 'MATCH_REJECT',
    PRO_REQUEST_APPROVED: 'PRO_REQUEST_APPROVED',
    PRO_REQUEST_REJECTED: 'PRO_REQUEST_REJECTED',
    PREMADE_JOINED: 'PREMADE_JOINED',
    STREAM_JOINED: 'STREAM_JOINED',
    ELITE_REQUEST: 'ELITE_REQUEST',
    ELITE_REQUEST_ADDED_PRO: 'ELITE_REQUEST_ADDED_PRO',
    ELITE_REQUEST_REJECTED: 'ELITE_REQUEST_REJECTED',
    ELITE_REQUEST_APPROVED: 'ELITE_REQUEST_APPROVED',
    NEW_MESSAGE: 'NEW_MESSAGE',
}
